cp -a ../mjd/CTcal.c .
cp -a ../mjd/CTcal2.c .
cp -a ../mjd/PSAcal.c .
cp -a ../mjd/PZcal.c .
cp -a ../mjd/decode_runfile_header.c .
cp -a ../mjd/ep_finalize.c .
cp -a ../mjd/ep_util.c .
cp -a ../mjd/eventbuild.c .
cp -a ../mjd/eventprocess.c .
cp -a ../mjd/pz_fitter.c .
cp -a ../mjd/siginspect.c .
cp -a ../mjd/skim.c .
cp -a ../mjd/sortskim.c .
cp -a ../mjd/sortrun.c .
cp -a ../mjd/runBits.h .
